# Generated by Django 4.2.20 on 2025-03-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.IntegerField(choices=[(1, 'Personal'), (2, 'Study'), (3, 'Work')], verbose_name='Recording tasks')),
                ('task_name', models.CharField(max_length=100, verbose_name='Name of the taks')),
                ('est_time', models.IntegerField(verbose_name='Estimated time')),
                ('moti', models.IntegerField(verbose_name='Motivation(0-10)')),
                ('actual_time', models.IntegerField(verbose_name='Actual Time Taken')),
                ('num_of_seatings', models.IntegerField(verbose_name='Number of seatings')),
                ('percent_completed', models.IntegerField(verbose_name='Percentage completion')),
                ('finished_time', models.IntegerField(choices=[(1, 'Morning'), (2, 'Day'), (3, 'Night')], verbose_name='Recording completed tasks')),
            ],
        ),
    ]
