# Generated by Django 4.2.20 on 2025-03-30 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_task_complete_task_register_delete_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_complete',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task_register',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='regstered_tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
