# Generated by Django 4.2.20 on 2025-03-30 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0003_task_complete_user_task_register_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.IntegerField(choices=[(1, 'Personal'), (2, 'Study'), (3, 'Work')])),
                ('task_name', models.CharField(max_length=100)),
                ('est_time', models.IntegerField()),
                ('moti', models.IntegerField()),
                ('actual_time', models.IntegerField()),
                ('num_of_seatings', models.IntegerField()),
                ('percent_completed', models.IntegerField()),
                ('finished_time', models.IntegerField(choices=[(1, 'Morning'), (2, 'Day'), (3, 'Night')])),
                ('task_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.task_register')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
