# Generated by Django 4.2.20 on 2025-03-30 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_tasksummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksummary',
            name='task_id',
        ),
    ]
