# Generated by Django 4.2.20 on 2025-03-30 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_tasksummary_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksummary',
            name='task_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.task_register'),
            preserve_default=False,
        ),
    ]
