# Generated by Django 4.2.20 on 2025-03-31 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_tasksummary_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksummary',
            name='task_id',
        ),
    ]
